// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test qa', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test qa', async function() {
    await driver.get("https://www.tascoappliance.ca/home/")
    await driver.manage().window().setRect({ width: 782, height: 864 })
    {
      const element = await driver.findElement(By.css(".w > .header__icons .header__quote"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".swiper-slide-next .appliances__item-front")).click()
    {
      const element = await driver.findElement(By.linkText("In-stock"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Price (Low to High)")).click()
    await driver.findElement(By.css(".catalogue__list-item:nth-child(3) img")).click()
    await driver.executeScript("window.scrollTo(0,500)")
    await driver.executeScript("window.scrollTo(0,599.2000122070312)")
    await driver.findElement(By.css(".add-to-cart")).click()
    await driver.findElement(By.css(".catalogue__popup-option:nth-child(3) .add-model-to-cart")).click()
    await driver.executeScript("window.scrollTo(0,300)")
    await driver.executeScript("window.scrollTo(0,2000)")
    await driver.findElement(By.id("BillingAddress_FirstName")).click()
    await driver.findElement(By.id("BillingAddress_FirstName")).sendKeys("asdf")
    await driver.findElement(By.id("BillingAddress_LastName")).click()
    await driver.findElement(By.id("BillingAddress_LastName")).sendKeys("asdf")
    await driver.findElement(By.id("BillingAddress_Email")).click()
    await driver.findElement(By.id("BillingAddress_Email")).sendKeys("asdf")
    await driver.findElement(By.id("BillingAddress_MobilePhone")).click()
    await driver.findElement(By.id("BillingAddress_Email")).click()
    await driver.findElement(By.id("BillingAddress_Email")).sendKeys("asdf@google.ca")
    await driver.findElement(By.id("BillingAddress_MobilePhone")).click()
    await driver.findElement(By.id("BillingAddress_MobilePhone")).sendKeys("3252543532")
    await driver.findElement(By.id("BillingAddress_City")).click()
    await driver.findElement(By.id("BillingAddress_City")).sendKeys("mississauga")
    await driver.findElement(By.id("BillingAddress_ZipCode")).click()
    await driver.findElement(By.id("BillingAddress_ZipCode")).sendKeys("n4b5b3")
    await driver.findElement(By.id("BillingAddress_Address1")).sendKeys("44 plain")
    await driver.findElement(By.id("CardInfo_CardHolder")).sendKeys("1234512345123451")
    await driver.findElement(By.id("CardInfo_CardNumber")).sendKeys("123451234512345")
    await driver.findElement(By.id("CardInfo_CVV")).sendKeys("123")
    await driver.findElement(By.id("Checkout")).click()
  })
})
